# Generated by Django 4.1.2 on 2022-10-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='shortened_link',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
